=== Adlik/Adlik/model_compiler/src/model_compiler/config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "properties": {
    "serving_type": {
      "type": "string",
      "enum": [
        "tf",
        "tensorrt",
        "openvino"
      ],
      "description": "target serving model type"
    },
    "model_name": {
      "type": "string",
      "description": "output model name"
    },
    "version": {
      "type": "integer",
      "minimum": 1,
      "description": "version number of output model"
    },
    "max_batch_size": {
      "type": "integer",
      "minimum": 1,
      "description": "maximum batch size of output serving model can support"
    },
    "input_model": {
      "type": "string",
      "description": "file path of a pre-trained model which can be Keras h5 model(*.h5), TensorFlow checkpoint or frozen graph(*.pb)"
    },
    "script_path": {
      "type": "string",
      "description": "file path of a model script which describes the model structure especially custom layers or operations , optional"
    },
    "input_layer_names": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "required when input model is Keras h5 model"
    },
    "output_layer_names": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "required when input model is Keras h5 model"
    },
    "input_formats": {
      "type": "array",
      "items": {
        "enum": [
          "channels_last",
          "channels_first",
          null
        ]
      },
      "description": "required when input is image"
    },
    "input_names": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "input tensor names, required when input model is TensorFlow checkpoint or frozen graph"
    },
    "output_names": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "output tensor names, required when input model is TensorFlow checkpoint or frozen graph"
    },
    "input_signatures": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "alias of inputs, required when serving_type is tf"
    },
    "output_signatures": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "alias of outputs, required when serving_type is tf"
    },
    "export_path": {
      "type": "string",
      "description": "path of output model"
    }
  },
  "required": [
    "serving_type",
    "model_name",
    "max_batch_size",
    "input_model",
    "export_path"
  ],
  "additionalProperties": true
}

=== Adlik/Adlik/benchmark/tests/test_model/mnist_tensorflow/serving_model.json
{
  "serving_type": "tf",
  "input_model": "model/frozen_graph.pb",
  "export_path":  "model_repos_tf2",
  "input_names": [
      "x:0"
  ],
  "output_names": [
      "Identity:0"
  ],
  "input_formats": [
      "channels_last"
  ],
  "input_signatures": [
      "image"
  ],
  "output_signatures": [
      "label"
  ],
  "model_name": "mnist",
  "max_batch_size": 128
}

=== Adlik/Adlik/benchmark/tests/test_model/mnist_keras/serving_model.json
{
  "serving_type": "openvino",
  "input_model": "model/mnist.h5",
  "export_path":  "model_repos",
  "input_layer_names": [
      "conv2d_1"
  ],
  "output_layer_names": [
      "dense_2"
  ],
  "input_formats": [
      "channels_last"
  ],
  "input_signatures": [
      "image"
  ],
  "output_signatures": [
      "label"
  ],
  "model_name": "mnist",
  "max_batch_size": 128
}

=== Adlik/Adlik/benchmark/tests/test_model/inceptionv3_keras/serving_model.json
{
  "serving_type": "tf",
  "input_model": "model/inceptionv3.h5",
  "export_path": "model_repos",
  "input_layer_names": [
    "input_1"
  ],
  "output_layer_names": [
    "predictions"
  ],
  "input_formats": [
    "channels_last"
  ],
  "input_signatures": [
    "image"
  ],
  "output_signatures": [
    "label"
  ],
  "model_name": "inceptionv3",
  "max_batch_size": 128
}

=== Adlik/Adlik/benchmark/tests/test_model/resnet50_keras/serving_model.json
{
  "serving_type": "tf",
  "input_model": "model/resnet50.h5",
  "export_path": "model_repos",
  "input_layer_names": [
    "input_1"
  ],
  "output_layer_names": [
    "fc1000"
  ],
  "input_formats": [
    "channels_last"
  ],
  "input_signatures": [
    "image"
  ],
  "output_signatures": [
    "label"
  ],
  "model_name": "resnet50",
  "max_batch_size": 128
}

=== Adlik/Adlik/benchmark/tests/test_model/resnet50_tensorflow/serving_model.json
{
  "serving_type": "tf",
  "input_model": "model/resnet50.ckpt",
  "export_path":  "model_repos",
  "input_names": [
      "input_1:0"
  ],
  "output_names": [
      "fc1000/Softmax:0"
  ],
  "input_formats": [
      "channels_last"
  ],
  "input_signatures": [
      "image"
  ],
  "output_signatures": [
      "label"
  ],
  "model_name": "resnet50",
  "max_batch_size": 128
}

=== Adlik/Adlik/benchmark/tests/test_model/inceptionv3_tensorflow/serving_model.json
{
  "serving_type": "tf",
  "input_model": "/model/inceptionv3.ckpt",
  "export_path":  "model_tf",
  "input_names": [
    "input_1"
  ],
  "input_formats": [
    "channels_last"
  ],
  "output_names": [
    "predictions/Softmax"
  ],
  "input_signatures": [
    "image"
  ],
  "output_signatures": [
    "label"
  ],
  "model_name": "inceptionv3",
  "max_batch_size": 128
}
